nginx-proxy-manager:
  container_name: nginx-proxy-manager
  build:
    context: ./.templates/nginx-proxy-manager/.
    args:
      - NGINX_PROXY_MANAGER_BASE=jc21/nginx-proxy-manager:latest
  restart: unless-stopped
  ports:
    # These ports are in format <host-port>:<container-port>
    - '80:80' # Public HTTP Port
    - '443:443' # Public HTTPS Port
    - '81:81' # Admin Web Port
    # Add any other Stream port you want to expose
    # - '21:21' # FTP

  # Uncomment the next line if you uncomment anything in the section
  # environment:
  # Uncomment this if you want to change the location of 
  # the SQLite DB file within the container
  # DB_SQLITE_FILE: "/data/database.sqlite"

  # Uncomment this if IPv6 is not enabled on your host
  # DISABLE_IPV6: 'true'

  volumes:
    - ./volumes/nginx/data/nginx/proxy_host:/data/nginx/proxy_host
    - ./volumes/nginx/data:/data
    - ./letsencrypt:/etc/letsencrypt
